name: danshulgin_login

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  another_flushbar: ^1.12.29
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  injectable_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/auth_failed.webp
    - assets/auth_successful.webp
